services:
  reminder-checker:
    image: reminder-checker
    build: .
    volumes:
      - ./Reminder.csv:/app/Reminder.csv
      - ./Ticker.csv:/app/Ticker.csv
    container_name: reminder_checker
    restart: unless-stopped
