services:
  portainer-ce:
    image: 'portainer/portainer-ce:latest'
    ports:
      - '9000:9000'
      - '8000:8000'
    container_name: portainer
    networks:
      - nginxproxymanager_default
    volumes:
      - '/home/amanpi5/portainer/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
networks:
  nginxproxymanager_default:
    external: true
